### ISSUE TITLE
WoRMS CoLDP export: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#7]
Data received on 2020-12-22.

@gdower imported in the clearinghouse:
**WoRMS Amphipoda dev** https://data.catalogueoflife.org/dataset/2248/classification?taxonKey=xG
**WoRMS Placozoa dev**  https://data.catalogueoflife.org/dataset/2249/taxon/x6
**WoRMS Mollusca dev**  https://data.catalogueoflife.org/dataset/2247/classification

**Comment by yroskov** [comment]
- [ ] No authorstrings with uninomials. (These data are present on WoRMS website)
@gdower says: They used the flat NameUsage format, so there are no author strings for the uninomials.

**Comment by mdoering** [comment]
the flat format is convenient sometimes, but not recommended as its less explicit. If possible they should switch to the main parent child format

**Comment by yroskov** [comment]
- [ ] How to manage not-assigned taxa, delivered in the export as Suborder **Amphipoda incertae sedis** (=not assigned suborder in parent order Amphipoda)?
(at the same time, I can see not-assigned taxa shown in the tree like this:
![image](https://user-images.githubusercontent.com/28574252/103936306-dfab9500-50ec-11eb-9953-0baa1d846d5a.png)

**Comment by yroskov** [comment]
- [ ] Another example of missing ranks (no taxa between top phylum Placozoa and family:

![image](https://user-images.githubusercontent.com/28574252/103936922-ad4e6780-50ed-11eb-9c7d-181db8f70651.png)

Example from **WoRMS Placozoa dev** https://data.catalogueoflife.org/dataset/2249/classification?taxonKey=x6

**Comment by mdoering** [comment]
The logic is you need to have an existing sibling rank to create a virtual group "Not assigned" for the same rank so that all children in the tree have the same rank - whatever rank that is. It is not based on major Linnean ranks or any other convention.

**Comment by mdoering** [comment]
> How to manage not-assigned taxa, delivered in the export as Suborder Amphipoda incertae sedis (=not assigned suborder in parent order Amphipoda)?

Not sure what exactly the question is. But ideally you simply have no record for incertae sedis taxa. 
If you do have them the name parser will flag them as "placeholder" name types which will be skipped during a COL sync, so they should not matter. Any name with "incertae sedis" in it will be considered a placeholder

**Comment by mdoering** [comment]
... If you use the denormalized, flat ColDP format just keep an empty string in the respective column

**Comment by yroskov** [comment]
> 
> 
> > How to manage not-assigned taxa, delivered in the export as Suborder Amphipoda incertae sedis (=not assigned suborder in parent order Amphipoda)?
> 
> Not sure what exactly the question is. But ideally you simply have no record for incertae sedis taxa.
> If you do have them the name parser will flag them as "placeholder" name types which will be skipped during a COL sync, so they should not matter. Any name with "incertae sedis" in it will be considered a placeholder

**Comment by yroskov** [comment]
- [ ] I am unable to check metadata. There are no metadata in "dev" versions.

Metadata need to be discussed with Bart & Khadija. At! split department, organization, city, country.

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/coldp/blob/master/metadata.yaml

**Comment by yroskov** [comment]
We agreed that metadata should be present in the clearinghouse. CoL may correct them via patches.

**Comment by gdower** [comment]
They've got a `-` at the top of the metadata.yaml file, which might cause the importer to fail, because usually it's supposed to be `---` at the top of a yaml file. I'll ask if they can fix that.

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/fIpVHHcBU86CouzbNMNR?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:dataset,negate:!f,params:(query:'2250'),type:phrase),query:(match_phrase:(dataset:'2250')))))&_g=(filters:!())):
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `life.catalogue.importer.coldp.MetadataParser$YamlDataset` out of START_ARRAY token
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1460)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at life.catalogue.importer.coldp.MetadataParser.readMetadata(MetadataParser.java:113)
	at life.catalogue.importer.coldp.MetadataParser.readMetadata(MetadataParser.java:101)
	at life.catalogue.importer.coldp.ColdpInserter.readMetadata(ColdpInserter.java:311)
	at life.catalogue.importer.Normalizer.insertData(Normalizer.java:873)
	at life.catalogue.importer.Normalizer.call(Normalizer.java:85)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:232)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mdoering** [comment]
Yes please. They can use a simple YAML validator to test the basic YAML format at least:
http://www.yamllint.com

A bad metadata file should not bring down the entire import though - just results in no metadata at all

**Comment by gdower** [comment]
Yeah, it still imported; just without metadata.

**Comment by gdower** [comment]
In order for their metadata to work they need to:
- eliminate the dashes at the top
- eliminate the indent
- separate the contact, authorsAndEditors, and organisations into their respective components (givenName, familyName, email, name, etc.)

I fixed the metadata for this dataset, which I can send to them as an example:

https://data.catalogueoflife.org/dataset/2250/meta

**Comment by yroskov** [comment]
- [ ] Metadata, **missing fields**
World List of Chaetognatha checked as an example: https://data.catalogueoflife.org/dataset/2250/meta

Alias (i.e. Short name. Should be "WoRMS + taxon" - how to create it and populate through all releases?)
[Organisations: see country name United States of America. Need to be corrected as USA]
[Version: should value contain word "ver."?]
Taxonomic coverage (english name)
Geographic scope
Checklist Confidence
Completeness

**Comment by mdoering** [comment]
I will add a metadata validation service to the API - it is hard to test otherwise.
The metadata parser should actually be able to parse some less structured metadata for contacts and organisations too, i.e. they should be able to just give a single string for a contact or organisation that will be tried to be parsed into given & family name for example. Not recommended, but some sources might not be able to provide the fully broken down metadata.

**Comment by mdoering** [comment]
The API shortly exposes 3 ways of parsing metadata:

```
// from a URL of a hosted file
curl http://api.catalogueoflife.org/parser/metadata?url={YOUR_METADAT_LOCATION}

// posting a yaml file
curl -X POST -H "Content-Type:text/yaml" --data-binary @metadata.yaml http://api.catalogueoflife.org/parser/metadata

// posting a yaml file via a html form
curl -X POST -H "Content-Type:text/yaml" --data-binary @metadata.yaml http://api.catalogueoflife.org/parser/metadata
```

The output will be the parsed JSON dataset object or an error.

**Comment by bart-v** [comment]
Related to the incomplete/non-structured fields in the YAML metadata: we have not fully developed that since we have the full metadata already in EML.
I assume many CoL providers will be in this situation (so why using yet another metadata (non?)standard...)

Thanks for raising this @gdower 
https://github.com/CatalogueOfLife/coldp/issues/43
